export const navbarData = [
    {
        id: 'about',
        name: 'ABOUT',
        href: '#about',
    },
    {
        id: 'experience',
        name: 'EXPERIENCE',
        href: '#experience',
    },
    {
        id: 'projects',
        name: 'PROJECTS',
        href: '#projects',
    },
    {
        id: 'contact',
        name: 'CONTACT',
        href: '#contact',
    },
];

export const projectData = [
    {
        id: '',
        name: '',
        desc: '',
        type: '',
        role: '',
        tech: [],
        link: '',
    },
    {
        id: '01',
        name: 'CovMo',
        desc: 'A large-scale telecom data analytics platform to provide geo-location, network optimization solutions, and mobility insights.',
        type: 'WEB APP',
        role: 'Front-end Engineer @ Groundhog Technologies',
        tech: ['TypeScript', 'React Hooks', 'Redux', 'Styled-Components', 'MapBox'],
        link: '',
    },
    {
        id: '02',
        name: 'ETL Scheduling',
        desc: 'A prototype dashboard to overview the data flow of ETL jobs with timeline charts and dynamic graphs.',
        type: 'WEB APP',
        role: 'Data Engineer @ Cathay Financial Holdings',
        tech: ['JavaScript', 'D3', 'Bootstrap'],
        link: '123',
    },
    {
        id: '03',
        name: 'Intention Mining',
        desc: 'A visual tool for viewing the online intentions that mining from website URL tags using clustering methods.',
        type: 'WEB APP',
        role: 'Data Engineer @ Cathay Financial Holdings',
        tech: ['JavaScript', 'D3', 'Bootstrap'],
        link: '123',
    },
    {
        id: '04',
        name: 'Medical Knowledge',
        desc: 'An innovative data visualization platform to control the mining association rules from the massive medical dataset.',
        type: 'WEB APP',
        role: 'Web Developer Intern @ Delta Electronics',
        tech: ['JavaScript', 'D3'],
        link: '123',
    },
    {
        id: '05',
        name: 'Healthcare Map',
        desc: 'An information retrieval system based on the map for searching millions of Taiwan healthcare data.',
        type: 'WEB APP',
        role: 'Web Developer Intern @ Delta Electronics',
        tech: ['JavaScript', 'D3', 'jQuery', 'PHP', 'SQL', 'LeafLet'],
        link: '123',
    },
    {
        id: '06',
        name: 'Epidemic Map',
        desc: 'A map visualization system to analyze disease trends and forecast epidemics from crawled PTT public opinion articles.',
        type: 'WEB APP',
        role: 'Postgraduate @ NCCU CS',
        tech: ['JavaScript', 'Python', 'Django', 'D3'],
        link: '123',
    },
    {
        id: '07',
        name: 'Fashion Style',
        desc: 'A clothing recommendation system that recommends products using styles and popularity learned from online fashion data.',
        type: 'WEB APP',
        role: 'Postgraduate @ NCCU CS',
        tech: ['JavaScript', 'Python', 'Django', 'PostgresDB'],
        link: '123',
    },
    {
        id: '08',
        name: 'Space Shooter',
        desc: 'A first-person shooter game with space animation materials.',
        type: '3D Game',
        role: 'Postgraduate @ NCCU CS',
        tech: ['C#', 'Unity'],
        link: '123',
    },
    {
        id: '',
        name: '',
        desc: '',
        type: '',
        role: '',
        tech: [],
        link: '',
    },
];
